# Use official Node image
FROM node:20-alpine

# Set work directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY frontend/ .

# Expose port
EXPOSE 3000

# Run Next.js development server
CMD ["npm", "run", "dev"]
