# Generated by Django 4.2.7 on 2025-10-02 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('number_of_locations', models.IntegerField(default=1)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='onboarding', max_length=20)),
                ('health_score', models.IntegerField(default=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('churned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new_lead', 'New Lead'), ('contact_made', 'Contact Made'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('contract_sent', 'Contract Sent'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new_lead', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Expected deal value', max_digits=10)),
                ('probability', models.IntegerField(default=10, help_text='Probability of closing (0-100%)')),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, choices=[('price', 'Price Too High'), ('competitor', 'Chose Competitor'), ('timing', 'Not Ready / Bad Timing'), ('no_budget', 'No Budget'), ('no_decision', 'No Decision Maker Buy-in'), ('other', 'Other')], max_length=20)),
                ('lost_reason_detail', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('proposal', 'Proposal Sent'), ('note', 'Note')], max_length=20)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Deal activities',
                'db_table': 'deal_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(help_text='City/Area', max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('converted', 'Converted to Customer')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('facebook', 'Facebook Ad'), ('instagram', 'Instagram Ad'), ('google', 'Google Ad'), ('referral', 'Referral'), ('sales_sourced', 'Sales Sourced (Google Maps, etc.)'), ('chat', 'Support Chat'), ('other', 'Other')], max_length=20)),
                ('campaign_id', models.CharField(blank=True, help_text='Marketing campaign ID', max_length=100)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_contact_due', models.DateTimeField(blank=True, help_text='First contact should be made by this time', null=True)),
                ('first_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
