# Generated by Django 4.2.7 on 2025-10-04 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(blank=True, help_text='Estimated monthly budget (e.g., $500-$1000)', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_status',
            field=models.CharField(choices=[('not_called', 'Not Called'), ('called', 'Called'), ('left_message', 'Left Message'), ('no_answer', 'No Answer'), ('meeting_scheduled', 'Meeting Scheduled')], default='not_called', help_text='Current contact status', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, help_text='Restaurant industry/category (e.g., Italian, Fast Food, Fine Dining)', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, help_text='Last time this lead was contacted', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='number_of_locations',
            field=models.IntegerField(default=1, help_text='Number of restaurant locations', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', help_text='Lead priority level', max_length=20),
        ),
    ]
