# Generated by Django 4.2.7 on 2025-10-05 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='churn_reason',
            field=models.CharField(blank=True, choices=[('price', 'Price Too High'), ('competitor', 'Switched to Competitor'), ('not_using', 'Not Using the Service'), ('bad_experience', 'Poor Customer Experience'), ('business_closed', 'Business Closed/Bankrupt'), ('technical_issues', 'Technical Problems'), ('missing_features', 'Missing Required Features'), ('no_support', 'Poor Support Quality'), ('seasonal', 'Seasonal Business (Temporary)'), ('contract_end', 'Contract Ended (No Renewal)'), ('other', 'Other Reason')], help_text='Primary reason for churn', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='churn_reason_detail',
            field=models.TextField(blank=True, help_text='Additional details about churn (optional)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible storage for custom data without schema changes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last time any team member interacted with this customer', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_activity_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_activity_type',
            field=models.CharField(blank=True, help_text='Type of last activity (call, email, meeting, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='ops_rep',
            field=models.ForeignKey(blank=True, help_text='Operations engineer responsible for technical deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='churn_reason',
            field=models.CharField(blank=True, choices=[('price', 'Price Too High'), ('competitor', 'Switched to Competitor'), ('not_using', 'Not Using the Service'), ('bad_experience', 'Poor Customer Experience'), ('business_closed', 'Business Closed/Bankrupt'), ('technical_issues', 'Technical Problems'), ('missing_features', 'Missing Required Features'), ('no_support', 'Poor Support Quality'), ('seasonal', 'Seasonal Business (Temporary)'), ('contract_end', 'Contract Ended (No Renewal)'), ('other', 'Other Reason')], help_text='Primary reason for churn', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='churn_reason_detail',
            field=models.TextField(blank=True, help_text='Additional details about churn (optional)'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible storage for custom data without schema changes'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last time any team member interacted with this customer', null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='last_activity_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='last_activity_type',
            field=models.CharField(blank=True, help_text='Type of last activity (call, email, meeting, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='ops_rep',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Operations engineer responsible for technical deployment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cs_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['churn_reason'], name='customers_churn_r_62b227_idx'),
        ),
    ]
